[Oauth2Provider] Issue with mass-assigment
Problem: At Redmine start the following error is raised "NoMethodError
(undefined method `attr_accessible' for
Songkick::OAuth2::Model::Client:Class"

Reason: Mass-assignment as been removed from Models in Rails 4.x and
should be done in Controller

Solution: The problem was solved in the last update of the gem songkick-oauth2-provider
but because the last version has not been released on rubygems it need
to be specified on the Gemfile to pull the dedicated tag